### ISSUE TITLE
a way to print out json without contacting the api

### ISSUE THREAD

**Issue by richlv** [whosgonna/Zabbix-Tiny.pm#11]
it could be useful to have a way to print out json before/without sending it to the api.
currently, if a request fails and we want to reasonably see what we sent, we have to eval the request (so that the script wouldn't exit before i can print the json).

that is doable, but a bit more complicated than just printing out the json.

additionally, one might want to do some tests and see json w/o a zabbix api endpoint available at the time, which would be even more complicated.

**Comment by whosgonna** [comment]
To run this without connecting to Zabbix server would require altering the constructor so that the `new` method wouldn't automatically connect.  I'm considering adding a parameter to delay the server connection until a do method is called (which could also function to automate a re-login if used in a long running script).  Given that the second portion of this request to use this without an endpoint is deferred at least until I work on a connection status check.

I see a few ways to go about getting the json string prior to sending to the server that I'm seeing.  The first is a dedicated method that does the same thing as `do` until the point of sending the message to the server.  This would be fairly simple to do, but it would also be rather redundant in terms of the coding.  For example:

```
my $params = {
    output    => [qw(hostid name host)], 
    monitored => 1,
};
my $json_string = $zabbix->create_json('host.get',$params);
say $json_string;
my $hosts = $zabbix->do('host.get',$params);  ## passing the same argument.
print Dumper $hosts;
```

This goes through the processes of encoding the json twice.  That's not really a ton of overhead since the params are a very small list even in the largest use case scenario.  It's just redundant.

The second is to add a `prepare` method that creates the json string, and could then be passed to the `do` method.  I'm not sure of the best way to create this interface.  Perhaps if do is called with no arguments like this:

```
my $params = {
    output    => [qw(hostid name host)], 
    monitored => 1,
};
$zabbix->prepare('host.get',$params);
say $zabbix->json_request;
my $hosts = $zabbix->do();  ## No argument uses prepared data.
print Dumper $hosts;
```

This doesn't LOOK spectacularly different from a coding standpoint, but it's potentially more efficient and cleaner in the back end.  This would also allow for `do` to be called repeatedly without having to re-encode the data to json.

I think the second idea is probably the proper way to go.

**Comment by whosgonna** [comment]
TODO:
1. Create a `request` attribute.  This will always store the data to be sent to the server as a perl data structure.
2. This is accessible to users as json with the `json_prepared` attribute.  (NOTE: `json_prepared` should be an attribute as well that is set when `request` is updated.  If it is just a method that calls `encode_json` on the `attribute` then the order of the data in the json string could change.  Functionally it should be the same, but since the request is to see the json string that will be sent, we should honor the order)
3. When `do` is called with arguments (as is normal historically), update the `request` attribute before sending the request.
4. `do` now always sends the `request` to the server (after converting to json).  If `do` is called with no arguments, then it uses the `requst` attribute.
5. The string sent is stored in `json_request`.  `json_request` remains the most recent string that was sent.
6. AFTER sending the request, `do` will update the `id` stored in the `request` attribute.

This means `request` is updated every time `do` is called.  If you `prepare`, then call `json_prepared`, you will see the json data that will be sent to the server on the next call to `do` (assuming no arguments are passed to `do`).  If `json_prepared` is called again, then the json string will have changed, in that the id value (and ONLY the id value) should be new.  Example:

```
my $params = {
    output    => [qw(hostid name host)], 
    monitored => 1,
};
$zabbix->prepare('host.get',$params);
say $zabbix->json_prepared;  ## "id" will XXXXX
say $zabbix->json_prepared;  ## "id" will STILL be XXXXX
my $hosts = $zabbix->do();
say $zabbix->json_prepared;  ## "id" will be YYYYY because XXXXX was used.
say $zabbix->json_request;  ## "id" is XXXXX because it reflects the last request sent.
$hosts = $zabbix->do();
say $zabbix->json_prepared;  ## "id" will be ZZZZZ because YYYYY was used.
say $zabbix->json_request;  ## "id" is YYYYY because it reflects the last request sent.
```

**Comment by whosgonna** [comment]
New version is pushed up to github.  Interally it's implemented slightly different than i noted above, however the public attributes and methods should be consistent with what's documented above.

Also, now login is delayed until the first `$zabbix->prepare` or `$zabbix->do` method is called, and re-login is automatic if the user logs out.  This makes the library useful for long running (daemon) programs.

I still need to provide documentation, but I think you should be able to start running with the changes I've just pushed.

**Comment by whosgonna** [comment]
Richlv,

Is this working for you?  I still need to update the POD to document the new feature, but I want to make sure it's complete first.

**Comment by whosgonna** [comment]
Documentation is complete.  Closing the issue.
