### ISSUE TITLE
do not pass 'auth' to apiinfo.version

### ISSUE THREAD

**Issue by richlv** [whosgonna/Zabbix-Tiny.pm#18]
for apiinfo.version, 'auth' must be excluded, otherwise : "Error: The "apiinfo.version" method must be called without the "auth" parameter"

it is probably worth having a special-case hack in zabbix::tiny, so that it is able to work with all the old versions of zabbix, even if this is changed in later zabbix versions.

**Comment by whosgonna** [comment]
Would it be OK as a separate method? Instead of ```$zabbix->do('ap info.version')```, have it be  ```$zabbix->version() ```?   It might even be possible to pass a separate URL here. 

Part of the complexity that I see is that Zabbix::Tiny is designed to take the user and password as semi-required attributes (possibly hard required, I'll have to check the code), so creating a special handling within the ```do``` arguments is more complex than just a separate method. It does create more special handling by the user of the module, though.

**Comment by richlv** [comment]
yeah, i think a separate method would be completely fine

**Comment by whosgonna** [comment]
This should be fixed in 9d5f111fd29b412d142521540fcea40e69b16e55.  I may try to find a few other minor issues (type-o's in POD, increment the version, add a few general case tests, etc.) prior to pushing to CPAN, but there shouldn't be any other logical changes prior to pushing to CPAN.

**Comment by whosgonna** [comment]
Closed.
