### ISSUE TITLE
passing data incorrectly results in an invalid api request

### ISSUE THREAD

**Issue by richlv** [whosgonna/Zabbix-Tiny.pm#2]
```
print Dumper(@usergroupids);
---------------------------------
$VAR1 = {
          'usrgrpid' => '55'
        };
$VAR2 = {
          'usrgrpid' => '13'
        };
---------------------------------
    my $user_created = $zabbix->do(
        'user.create',
        alias    => "temporary_test",
        passwd => "aaa",
        usrgrps => @usergroupids,
    );
```

it sort of prints an error :
Odd number of elements in hash assignment at lib/Zabbix/Tiny.pm line 74.

but still sends, as part of the json, the following to the zabbix api :
"params":{"passwd":"aaa","HASH(0x2c57570)":null,"alias":"temporary_test","usrgrps":{"usrgrpid":"55"}}

from the user perspective, it would probably be better if such errors would not lead to the actual api query being executed

**Comment by whosgonna** [comment]
I'll try to think of a way to solve this, but the problem is not only the odd number of elements (though that's part of it), but also with passing an array of hashrefs to the paramters for the user.create method.  To illustrate

```
my @usergroupids = ({usrgrpid => 55}, {usrgrpid => 13});
my %params = (
    alias    => "temporary_test",
    passwd => "aaa",
    usrgrps => @usergroupids,
);
print Dumper %params;
print encode_json({%params});
--------------------------------------------
$VAR1 = 'passwd';
$VAR2 = 'aaa';
$VAR3 = 'HASH(0x801c9a798)';
$VAR4 = undef;
$VAR5 = 'usrgrps';
$VAR6 = {
          'usrgrpid' => 55
        };
$VAR7 = 'alias';
$VAR8 = 'temporary_test';
{"passwd":"aaa","alias":"temporary_test","HASH(0x801c9a798)":null,"usrgrps":{"usrgrpid":55}}
```

Since `@usergroupids` is an array, it adds two items into the hash, thus the first value in `@usergroupids` is the value of usrgrps, and the second value is read as a new key. It would be like creating the hash in this manner (number on the left is just my counting the number of items, and not part of the code.  first item is the key, second is the value):

```
    my %params = (
k1        'alias',
v1        'temporary_test',
k2        'passwd',
v2        'aaa',
k3        'usrgrps',
v3        {usrgrpid => 55},  # First value in @usergroupids. This is a hashref.
k4        {usrgrpid => 13},  # Second value in @usergroupids.  No value follows.
)
```

The lack of a value here causes the warning about odd number of elements.  The warning will go away if a third hashref were to be added to the @usergroupids.  For example, `my @usergroupids = ({usrgrpid => 55}, {usrgrpid => 13}, {usrgrpid => 20});`, would provide a value as 'v4' in the table above, however it would not stop {usrgrpid => 13} from being assigned as the key, and the resulting HASH(0x...) in the json.

I also think that even if the `@usergroupids` were converted to an arrayref (enclosing it brackets:  `usrgrps => [@usergroupids],), it would still not yield the desired json because it would have repeating 'usrgrps'.  For example, simply adding brackets to the original example, produces the following json:

```
{
    "alias": "temporary_test",
    "passwd": "aaa",
    "usrgrps": [
        {
            "usrgrpid": 55
        },
        {
            "usrgrpid": 13
        }
    ],
}
```

Note that this is a repetition of the "usrgrpid".  My guess is that the Zabbix API expects something like this instead (where there is a single usrgrpid key which contains an array of values):

```
{
    "alias": "temporary_test",
    "passwd": "aaa",
    "usrgrps": [
        {
            "usrgrpid": [
                            55,
                            13
                         ]
        }
    ],
}
```

This would be accomplished by passing only the **values** from @usergroupids  to the params:

```
my @usergroupids = ({usrgrpid => 55}, {usrgrpid => 13});
my @usrgrpids;
for my $group (@usergroupids) {
    push @usrgrpids, $group->{usrgrpid};
}
my %params = (
    alias    => "temporary_test",
    passwd => "aaa",
    usrgrps => [@usrgrpids],
);
print Dumper %params;
print encode_json({%params});
---------------------------------------
$VAR1 = 'passwd';
$VAR2 = 'aaa';
$VAR3 = 'alias';
$VAR4 = 'temporary_test';
$VAR5 = 'usrgrps';
$VAR6 = [
          55,
          13
        ];
{"passwd":"aaa","usrgrps":[55,13],"alias":"temporary_test"}
```

Now....with all of it typed out so I can read it, it looks like the problem is just that encode_json doesn't handle references as keys very well.  I think it should be possible to loop through the %params hash, checking the keys to confirm that they are scalar prior to encode_json, and die if they are not.

**Comment by richlv** [comment]
just for the record, zabbix api does expect repeating usrgrpid like that - see https://www.zabbix.com/documentation/3.0/manual/api/reference/user/create for an example
