### ISSUE TITLE
Error: SQL statement execution has failed 

### ISSUE THREAD

**Issue by xrusteg** [whosgonna/Zabbix-Tiny.pm#9]
When I try to do $zabbix->do('hostgroup.create', name => ['Name]);
I get Error: SQL statement execution has failed "INSERT INTO groups (name,groupid) VALUES (Array,'8')". at ./topology.pl line 42.
The same when try to do with map.delete:
$zabbix->do('map.delete', '1') 
Error: SQL statement execution has failed "DELETE FROM sysmaps_elements WHERE elementid=Array AND elementtype='1'

But it works if do this without module:
$json = {
    jsonrpc => "2.0",
    method => "map.delete",
    params => ["$sysmapid"],
    id => 1,
    auth => $authID
};
$client->call($url, $json);

**Comment by whosgonna** [comment]
Can you provide a more complete example?   What is the zabbix server and front end versions? 

I think the first example should be:

$zabbix->do('hostgroup.create', name => $name);

Not

$zabbix->do('hostgroup.create', name => ['Name]);

The name argument takes a single value, not an array (even a single element array as indicated here).

Ill look into the map.delete function. It seems odd (but correct) that it only takes a single argument,  rather than a hash.

**Comment by whosgonna** [comment]
I'm fairly sure the hostgroup.create example you're citing is just a coding issue of using an arrayref where you should use a scalar.

WIth regards to map.delete (and other *.delete functions), it looks like they take a single array as the params argument.  While I feel that this is a poor choice on the part of the zabbix API, we're probably not going to get anywhere going down that road.

One of the goals was to not have to re-implement individual zabbix API methods in this module, so i'm hesitant to check the zabbix method and behave differently based off of that alone.

I think the solution will probably be to make `do` take only two arguments, the method, followed by an arrayref OR hashref, which should allow for proper message formatting.  It may take a week or two to get around to this.   Thank you for the problem report!

**Comment by whosgonna** [comment]
I've just pushed a patch to github, but i'd like you to test it before updating CPAN.

Previously, a hash was used to pass parameters.  For example:

```
my %params = ( groupids => 12345, limit => 1 );
$zabbix->do( 'host.get', %params );
```

The *.delete example cited does not use key => value pairs, so when i tried to do the following, it failed to properly create the params hash within the module:

`$zabbix->do('map.delete', '1');`

I've added a check so that if there is only two arguments to the do method, the first argument remains the zabbix method, however the second argument should be considered a reference. Note that a reference is a single argument, regardless of how many elements it contains.  Thus, the correct way to do the map.delete would now use an arrayref like this:

`$zabbix->do('map.delete', ['1']);`

The above cited host.get example can also utilize a hashref, like so:

```
my $params = { groupids => 12345, limit => 1};
$zabbix->do( 'host.get', $params );
```

Of course, you don't need to set a separate $params value. An anonymous hashref works equally well:

`$zabbix->do( 'host.get',  { groupids => 12345, limit => 1} );`

Please let me know if this works for you.

**Comment by whosgonna** [comment]
The module is updated on CPAN to include the fix. I believe it should work if you pass params as a reference.  Can you please test?

**Comment by xrusteg** [comment]
Thanks for the answer and the solution. I can confirm, now it works correct. I use zabbix 2.4.7.
